apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - name: file-server
        image: filebrowser/filebrowser:latest
        volumeMounts:
          - mountPath: /srv
            name: webroot
      volumes:
        - name: webroot
          csi:
            driver: local.csi.aliyun.com
            fsType: ext4                # 此处指定文件系统，可为 ext4、xfs
            volumeAttributes:
              vgName: open-local-pool-0 # 【必填】临时卷所用的 VG
              size: 1Gi                 # 【选填】临时卷大小，不填默认为 1 Gi