apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
spec:
  volumeSnapshotClassName: open-local-lvm
  source:
    # 需执行快照的源PVC名称
    persistentVolumeClaimName: html-example-lvm-0
