apiVersion: v1
kind: Service
metadata:
  name: nginx-lvm-snap
  labels:
    app: nginx-lvm-snap
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-lvm-snap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-lvm-snap
spec:
  selector:
    matchLabels:
      app: nginx-lvm-snap
  podManagementPolicy: Parallel
  serviceName: "nginx-lvm-snap"
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: html
    spec:
      dataSource:
        name: new-snapshot-test # 指定刚创建的VolumeSnapshot名称
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
      accessModes:
        - ReadWriteOnce
      storageClassName: open-local-lvm
      resources:
        requests:
          storage: 4Gi
  template:
    metadata:
      labels:
        app: nginx-lvm-snap
    spec:
      runtimeClassName: kata-qemu
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: nginx
        image: zcy-Z390-AORUS-MASTER.sh.intel.com/redis:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/data"
          name: html
        command:
        - sh
        - "-c"
        - |
            while true; do
              echo "huizhi testing";
              echo "yes ">>/data/yes.txt;
              sleep 120s
            done;