apiVersion: v1
kind: Service
metadata:
  name: example-lvm
  labels:
    app: example-lvm
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: example-lvm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-lvm
spec:
  selector:
    matchLabels:
      app: example-lvm
  podManagementPolicy: Parallel
  serviceName: "example-lvm"
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: html
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: open-local-lvm
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        app: example-lvm
    spec:
      runtimeClassName: kata-qemu
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: example-lvm
        image: zcy-Z390-AORUS-MASTER.sh.intel.com/redis:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/data"
          name: html
        command:
        - sh
        - "-c"
        - |
            while true; do
              echo "huizhi testing";
              echo "yes ">>/data/yes.txt;
              sleep 120s
            done;
